In [23]:
import pandas as pd
import numpy as np

from snorkel.labeling import labeling_function
from snorkel.labeling import PandasLFApplier

@labeling_function()
def is_big_num(x):
    return 1 if x.num > 52 else 0


dict1 = dict(num=[10, 100], text=["hello", "hi"])
df = pd.DataFrame(dict1)
# df = pd.DataFrame(dict(num=[10, 100], text=["hello", "hi"]))

applier = PandasLFApplier([is_big_num])
"""
PandasLFApplier
    parameter: df
    returns ndarray of labels
"""
# result = applier.apply(pd.DataFrame(dict(num=[10, 100], text=["hello", "hi"])))
result = applier.apply(df)  #  array([[0], [1]])

dict2 = dict(num=[10, 100],num2=[1151, 51], text=["hello", "hi"])
df2 = pd.DataFrame(dict2)
result2 = applier.apply(df2)


dict3 = dict(num2=[1141, 41], num=[10, 100], text=["hello", "hi"])
df3 = pd.DataFrame(dict3)
result3 = applier.apply(df3)

dict4 = dict(num=[1141, 41], num2=[10, 100], text=["hello", "hi"])
df4 = pd.DataFrame(dict4)
result4 = applier.apply(df4)

dict5 = dict(num2=[10, 100], text=["hello", "hi"],num=[1141, 41] )
df5 = pd.DataFrame(dict5)
result5 = applier.apply(df5)  # array([[1], [0]])

# https://www.moonbooks.org/Articles/How-to-store-a-multidimensional-matrix-in-a-dataframe-with-pandas-/Edit/
data = np.random.randint(100,size=(3,3,3))

print(data)
print(data[1,1,0])
# df_new = pd.DataFrame(data)  doesn't work

data = data.reshape(9,3)

print("data = ", data)

iterables = [[0,1,2], [0,1,2]]

index = pd.MultiIndex.from_product(iterables, names=['i', "j"])

df = pd.DataFrame(data=data, index=index, columns = [0,1,2])

df = df.rename_axis("k", axis="columns")

print("df  ", df)
print("df[1] = ", df[1])
# print(df['i'==1]['j'==1]['k'==0])
# df.loc[("bar", "two"), "A"]
df.loc[(0,0)]
print("df.loc[(0,0)] = ", df.loc[(0,0)])
print("df.loc[(0,0), 0] = ", df.loc[(0,0), 0])

print("df.loc[(0,0,0)] = ", df.loc[(0,0,0)])


100%|██████████| 2/2 [00:00<00:00, 1966.85it/s]


[[[25  1 25]
  [25 75 62]
  [74 22 75]]

 [[59  4 91]
  [91 49 97]
  [89 96  9]]

 [[63 34 32]
  [22 74 90]
  [34 25 99]]]
91
data =  [[25  1 25]
 [25 75 62]
 [74 22 75]
 [59  4 91]
 [91 49 97]
 [89 96  9]
 [63 34 32]
 [22 74 90]
 [34 25 99]]
df   k     0   1   2
i j            
0 0  25   1  25
  1  25  75  62
  2  74  22  75
1 0  59   4  91
  1  91  49  97
  2  89  96   9
2 0  63  34  32
  1  22  74  90
  2  34  25  99
df[1] =  i  j
0  0     1
   1    75
   2    22
1  0     4
   1    49
   2    96
2  0    34
   1    74
   2    25
Name: 1, dtype: int64
df.loc[(0,0)] =  k
0    25
1     1
2    25
Name: (0, 0), dtype: int64
df.loc[(0,0), 0] =  25


IndexingError: Too many indexers