In [8]:
import pandas as pd
import numpy as np

# https://www.moonbooks.org/Articles/How-to-store-a-multidimensional-matrix-in-a-dataframe-with-pandas-/Edit/
data = np.random.randint(100,size=(3,3,3))  # a 3-dim ndarray
data4d = np.random.randint(100,size=(3,3,3,3))  # a 3-dim ndarray

print("data = ", data)
print("data4d = \n", data4d)
print("data[1,1,0] = ",data[1,1,0])
# df_new = pd.DataFrame(data)  doesn't work

# make a 3-dim dataframe:

data = data.reshape(9,3)
print("reshaped data = \n", data)
iterables = [[0,1,2], [0,1,2]]
index = pd.MultiIndex.from_product(iterables, names=['i', "j"])
df = pd.DataFrame(data=data, index=index, columns = [0,1,2])
df = df.rename_axis("k", axis="columns")

print("df  ", df)
print("df[1] = ", df[1])

df.loc[(0,0)]
print("df.loc[(0,0)] = ", df.loc[(0,0)])
print("df.loc[(0,0), 0] = ", df.loc[(0,0), 0])

# print("df.loc[(0,0,0)] = ", df.loc[(0,0,0)])


data =  [[[22 82 20]
  [11  0 69]
  [78 61 75]]

 [[35 69 27]
  [ 9 55 17]
  [30 88 71]]

 [[30 11 35]
  [38 52 40]
  [57 40 46]]]
data4d = 
 [[[[48 11 28]
   [42 67 94]
   [16 16 32]]

  [[56 44 70]
   [ 2 71 13]
   [60 34 59]]

  [[42 22 29]
   [16 48 88]
   [36 35 21]]]


 [[[23 41 83]
   [89 80 94]
   [26 12 33]]

  [[35 29 85]
   [29 72 92]
   [67 60 56]]

  [[48 75 93]
   [ 4 47 77]
   [43 31 52]]]


 [[[83  3  0]
   [92 48 80]
   [14 20 48]]

  [[ 0 37  3]
   [19 46 58]
   [27 12 34]]

  [[34 33 38]
   [68 99 72]
   [42 58 41]]]]
data[1,1,0] =  9
reshaped data =  [[22 82 20]
 [11  0 69]
 [78 61 75]
 [35 69 27]
 [ 9 55 17]
 [30 88 71]
 [30 11 35]
 [38 52 40]
 [57 40 46]]
df   k     0   1   2
i j            
0 0  22  82  20
  1  11   0  69
  2  78  61  75
1 0  35  69  27
  1   9  55  17
  2  30  88  71
2 0  30  11  35
  1  38  52  40
  2  57  40  46
df[1] =  i  j
0  0    82
   1     0
   2    61
1  0    69
   1    55
   2    88
2  0    11
   1    52
   2    40
Name: 1, dtype: int6