In [9]:
import pandas as pd
import numpy as np

# https://www.moonbooks.org/Articles/How-to-store-a-multidimensional-matrix-in-a-dataframe-with-pandas-/Edit/
data = np.random.randint(100,size=(3,3,3))  # a 3-dim ndarray
data4d = np.random.randint(100,size=(3,3,3,3))  # a 3-dim ndarray

print("data = ", data)
print("data4d = \n", data4d)
print("data[1,1,0] = ",data[1,1,0])
# df_new = pd.DataFrame(data)  doesn't work

# make a 3-dim dataframe:

data = data.reshape(9,3)
print("reshaped data = \n", data)
iterables = [[0,1,2], [0,1,2]]
index = pd.MultiIndex.from_product(iterables, names=['i', "j"])
df = pd.DataFrame(data=data, index=index, columns = [0,1,2])
df = df.rename_axis("k", axis="columns")

print("df  ", df)
print("df[1] = ", df[1])

df.loc[(0,0)]
print("df.loc[(0,0)] = ", df.loc[(0,0)])
print("df.loc[(0,0), 0] = ", df.loc[(0,0), 0])

# print("df.loc[(0,0,0)] = ", df.loc[(0,0,0)])


data =  [[[73 90 67]
  [30  5 23]
  [94  9 98]]

 [[27 52 20]
  [49 55 30]
  [10 40 24]]

 [[72  2 38]
  [79 22 44]
  [32 47 73]]]
data4d = 
 [[[[ 7 65 97]
   [64 21 47]
   [33 87 45]]

  [[79 85 12]
   [28 36 11]
   [19 72 87]]

  [[48 24 67]
   [94  2 38]
   [54 43 68]]]


 [[[29 45 30]
   [13 79 77]
   [27 46 10]]

  [[89 15 50]
   [99 99 62]
   [16 62 78]]

  [[52 26 84]
   [96 98 11]
   [39 71 21]]]


 [[[65 74 69]
   [91 19 52]
   [20 78 89]]

  [[ 9 24 96]
   [14 78 65]
   [55 65 51]]

  [[59 60 76]
   [77 20 27]
   [43 24  7]]]]
data[1,1,0] =  49
reshaped data = 
 [[73 90 67]
 [30  5 23]
 [94  9 98]
 [27 52 20]
 [49 55 30]
 [10 40 24]
 [72  2 38]
 [79 22 44]
 [32 47 73]]
df   k     0   1   2
i j            
0 0  73  90  67
  1  30   5  23
  2  94   9  98
1 0  27  52  20
  1  49  55  30
  2  10  40  24
2 0  72   2  38
  1  79  22  44
  2  32  47  73
df[1] =  i  j
0  0    90
   1     5
   2     9
1  0    52
   1    55
   2    40
2  0     2
   1    22
   2    47
Name: 1, dtype: in